### ISSUE TITLE
Cache and clean up database connections

### ISSUE THREAD

**Issue by poundifdef** [scratchdata/ScratchDB#90]
Today, every time we perform any DB operation, we create a new connection. Instead we should cache them.

Today, we do the following to get a database connection:
 ``` go
conn := s.DB.GetDatabaseConnection(dbID)
destinations.GetDestination(conn)
```
Is there a cleaner way to do this? 

Second, once we establish a connection with a destination, we should try and maintain it, rather than closing the connection every time. Connection management should be transparent to anyone who is doing an insert/query to that destination.

**Comment by sd1li** [comment]
On cleaner way:
It can be simplified with a method that calls those two functions e.g. `db.GetDestination(dbID)`  since most/all uses of `GetDestination` first calls `GetDatabaseConnection`.

On caching:
DuckDB uses `database/sql` which is a pool, and clickhouse appears to also be a pool so I think we just need to open them once and re-use the same instance everywhere.

`GetDestination` would then call a constructor e.g. `duckdb.Open` that initializes the config and opens the database then cache the result keyed by `DatabaseConnection`.

AFAICT, the `DatabaseConnection` is never changed once it's loaded from the config file, so it should  be enough to cache the destination based on the `ID`, but we can also use a deterministic/`canconical` JSON encoder to generate a stable key or just store them as a slice and do a deep equality check to find the right one.

**Comment by poundifdef** [comment]
How shall we have a separation of concerns between the database (which only stores credentials) and the connection itself? Does there need to be some sort of DatabaseConnectionFactory which takes a DB as input and then maintains or caches Destination objects?

**Comment by sd1li** [comment]
I don't think much needs to change in the way of architecture. We can implement it in `GetDestination`. It'd just maintain a global cache instead of creating new objects every time.

It'd look something like this:



	// pkg/.../duckdb.go
	func pkg_duckdb__Open(connectionSettings map[string]any) (*duckdb.DuckDBServer, error) {
		// ...
		s := util.ConfigToStruct[*duckdb.DuckDBServer](connectionSettings)
		connector, err := s.getConnector()
		if err != nil {
			return nil, err
		}

		s.db = sql.OpenDB(connector)
		return s, nil
	}

	var (
		destinationCache = map[string]DatabaseServer{}
	)

	func deriveDatabaseConnectionKey(dbConfig models.DatabaseConnection) string {
		return dbConfig.ID
		// or
		// JSON map order is non-deterministic so we can use a package specfically designed
		// to return deterministic output
		// return canonicaljson.Marshal(dbConfig)
	}

	func GetDestination(dbConfig models.DatabaseConnection) (DatabaseServer, error) {
		// the dbserver is backed by a pool
		// so it's fine to always use the same instance, given the same settings
		key := deriveDatabaseConnectionKey(dbConfig)
		if srv, ok := destinationCache[key]; ok {
			return srv, nil
		}

		var srv DatabaseServer
		var err error
		switch dbConfig.Type {
		case "duckdb":
			srv, err = pkg_duckdb__Open(dbConfig.ConnectionSettings)
		// case ...
		default:
			err = fmt.Errorf("Invalid destintion type '%s'", dbConfig.Type)
		}
		if err != nil {
			return nil, err
		}
		destinationCache[key] = srv
		return srv, nil
	}
